namespace DHSIntegrationAgent.Contracts.Persistence;

public sealed record ProviderExtractionConfigRow(
    string ProviderCode,
    string? ClaimKeyColumnName,
    string? HeaderSourceName,
    string? DetailsSourceName,
    string? DoctorSourceName,
    string? ServiceSourceName,
    string? DiagnosisSourceName,
    string? LabSourceName,
    string? RadiologySourceName,
    string? AttachmentSourceName,
    string? OpticalSourceName,
    string? ItemDetailsSourceName,
    string? AchiSourceName,
    string? DateColumnName,
    string? CustomHeaderSql,
    string? CustomServiceSql,
    string? CustomDiagnosisSql,
    string? CustomLabSql,
    string? CustomRadiologySql,
    string? CustomOpticalSql,
    string? CustomItemSql,
    string? CustomAchiSql,
    string? Notes,
    DateTimeOffset UpdatedUtc);
